"""baseline schema snapshot

Revision ID: 265c12770c3f
Revises: 
Create Date: 2026-07-12 21:36:55.179818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from geoalchemy2 import Geometry

# revision identifiers, used by Alembic.
revision: str = '265c12770c3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_geospatial_table('police_unit_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('location', Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_geospatial_index('idx_police_unit_history_location', 'police_unit_history', ['location'], unique=False, postgresql_using='gist', postgresql_ops={})
    op.create_index(op.f('ix_police_unit_history_id'), 'police_unit_history', ['id'], unique=False)
    op.create_index(op.f('ix_police_unit_history_recorded_at'), 'police_unit_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_police_unit_history_unit_id'), 'police_unit_history', ['unit_id'], unique=False)
    op.drop_index(op.f('ix_crime_events_timestamp'), table_name='crime_events')
    op.create_index('ix_crime_events_timestamp', 'crime_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_crime_events_timestamp', table_name='crime_events')
    op.create_index(op.f('ix_crime_events_timestamp'), 'crime_events', [sa.literal_column('timestamp DESC')], unique=False)
    op.drop_index(op.f('ix_police_unit_history_unit_id'), table_name='police_unit_history')
    op.drop_index(op.f('ix_police_unit_history_recorded_at'), table_name='police_unit_history')
    op.drop_index(op.f('ix_police_unit_history_id'), table_name='police_unit_history')
    op.drop_geospatial_index('idx_police_unit_history_location', table_name='police_unit_history', postgresql_using='gist', column_name='location')
    op.drop_geospatial_table('police_unit_history')
    # ### end Alembic commands ###
