"""add dispatch and arrival timestamps

Revision ID: d51073ab7a8f
Revises: d59c192f8c15
Create Date: 2026-07-13 01:13:07.251731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51073ab7a8f'
down_revision: Union[str, Sequence[str], None] = 'd59c192f8c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crime_events', sa.Column('dispatched_at', sa.DateTime(), nullable=True))
    op.add_column('crime_events', sa.Column('arrived_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crime_events', 'arrived_at')
    op.drop_column('crime_events', 'dispatched_at')
    # ### end Alembic commands ###
