"""add dispatch fields to crime_events

Revision ID: d59c192f8c15
Revises: 265c12770c3f
Create Date: 2026-07-12 21:41:18.232754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59c192f8c15'
down_revision: Union[str, Sequence[str], None] = '265c12770c3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crime_events', sa.Column('assigned_unit_id', sa.String(), nullable=True))
    op.add_column('crime_events', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_crime_events_assigned_unit_id'), 'crime_events', ['assigned_unit_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crime_events_assigned_unit_id'), table_name='crime_events')
    op.drop_column('crime_events', 'resolved_at')
    op.drop_column('crime_events', 'assigned_unit_id')
    # ### end Alembic commands ###
